### ISSUE TITLE
512 plugins (ESP/ESPFE/ESM) regardless of whether active breaks loading

### ISSUE THREAD

**Issue by alandtse** [Nightfallstorm/SkyrimVRESL#31]
Examples of brokenness.

1. `coc whiterun` is not recognized anymore.
2. Continuing or loading any save file will hang
3. Skyrimvresl.log will not return small files (but will enumerate regular plugins) at `kDataLoaded: Printing loaded file

[skyrimvresl.log](https://github.com/Nightfallstorm/SkyrimVRESL/files/13632983/skyrimvresl.log)

Internal discord discussing it: https://discord.com/channels/509719897106939914/813836814414381117/1183667089735700550

**Comment by RafearTheModder** [comment]
Could this be related to the maximum file handle limit being only 512 unmodded, and fixed by running engine fixes with the "maxstdio" patch turned on? This sounds very familiar to something I had read about that patch before.

**Comment by alandtse** [comment]
Per @powerof3 Fixed by EngineFixes due to running out of handles.

```ini

[Patches]
MaxStdio = true                          ; Sets the maximum number of open file handles to 2048 (default 512), preventing the game from running out with large plugin counts (fixes true save corruption)
```

Probably fixed but might be worth warning about.

**Comment by alandtse** [comment]
> Could this be related to the maximum file handle limit being only 512 unmodded, and fixed by running engine fixes with the "maxstdio" patch turned on? This sounds very familiar to something I had read about that patch before.

Lol, thanks @RafearTheModder. Yes, you're right. Po3 saw it an knew it immediately.

**Comment by alandtse** [comment]
[EngineFixes ](https://www.nexusmods.com/skyrimspecialedition/mods/62089)currently is a boolean that sets to 2048. This may be enough but it may be worth making it settable. [Buffout 4 NG ](https://www.nexusmods.com/fallout4/mods/64880?tab=posts)did allow 8192 but ran into crashes for flat.

![image](https://github.com/Nightfallstorm/SkyrimVRESL/assets/7086117/7dd028db-aaab-44a0-8dd3-42f8a08f33ff)

**Comment by alandtse** [comment]
TODO: Update the code to check for EngineFixes and/or the setting and spit out a real warning?

https://github.com/rollingrock/EngineFixesVR/blob/d936583776561053421a4c6bed0d9de440d53556/patches/miscpatches.cpp#L160-L181

**Comment by alandtse** [comment]
Keeping this so we can print a warning if maxstdio isn't high enough. Low priority but probably post release.
