### ISSUE TITLE
Engine Fixes VR warning is always firing

### ISSUE THREAD

**Issue by alandtse** [Nightfallstorm/SkyrimVRESL#41]
The test may be too early. Or perhaps we need to simplify it to detecting enginefixesvr being available.

Moving to DataLoaded results in not warning in time. Currently trying to move it later from it's current position during load.

**Comment by rollingrock** [comment]
is this something i need to fix in engine fixes?

**Comment by Nightfallstorm** [comment]
We could try using the SKSE::MessagingInterface and run it on `kPostLoad`/`kPostPostLoad`? That would guarantee engine fixes VR gets to run its startup logic before we check the maxstdio

**Comment by alandtse** [comment]
Yah, I've moved it there with no effect. It may be the call to getmaxstdio just doesn't work. Gotta reread how EF patches.

**Comment by alandtse** [comment]
> is this something i need to fix in engine fixes?

No. Nothing for you to do. It's entirely a bug in my code here.

**Comment by rollingrock** [comment]
ok cool if i can help let me know

**Comment by alandtse** [comment]
Closed by #48
